trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Restore .NET Tools
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'

- task: DotNetCoreCLI@2
  displayName: Run Cake Build Script
  inputs:
    command: 'custom'
    custom: 'cake'
    arguments: '--Target=Build --Configuration=Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: 'test'
    arguments: '--collect:"XPlat Code Coverage" --configuration:Release --no-build'
    testRunTitle: 'Combined (Integration + Unit) Tests'

- task: PublishCodeCoverageResults@1
  displayName: Publish Code Coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: './Tests/**/coverage.cobertura.xml'
    failIfCoverageEmpty: true