trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - script: "dotnet tool restore"
    displayName: "Restore .NET Tools"

  - script: "dotnet cake --Configuration=$(buildConfiguration)"
    displayName: "Run Cake Build Script"

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      searchFolder: '$(Build.SourcesDirectory)'
      mergeTestResults: true
      failTaskOnFailedTests: true

  - task: PublishBuildArtifacts@1
    displayName: "Publish Release Artifact"
    inputs:
      artifactName: Release
      pathToPublish: $(Build.SourcesDirectory)/Artifacts/Build/Release
      publishLocation: Container

  - task: PublishBuildArtifacts@1
    displayName: "Publish Code Coverage Report Artifacts"
    inputs:
      artifactName: CoverageReports
      pathToPublish: $(Build.SourcesDirectory)/Artifacts/Test/CoverageReports
      publishLocation: Container
