trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  displayName: Restore .NET Tools
  inputs:
    command: 'custom'
    custom: 'tool'
    arguments: 'restore'

- task: DotNetCoreCLI@2
  displayName: Run Cake Build Script
  inputs:
    command: 'custom'
    custom: 'cake'
    arguments: '--Configuration=Release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'Tests/**/coverage.cobertura.xml'