trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet tool restore
  displayName: Restore .NET Tools

- script: dotnet cake --Configuration=$(buildConfiguration)
  displayName: Run Cake Build Script

- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Build.SourcesDirectory)/Tests/**/coverage.cobertura.xml'
    additionalCodeCoverageFiles: '$(Build.SourcesDirectory)/Artifacts/Test/CoverageReports'
    failIfCoverageEmpty: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.SourcesDirectory)/Artifacts'
    ArtifactName: 'myArtifacts'
    publishLocation: 'Container'
