trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - script: "dotnet tool restore"
    displayName: "Restore .NET Tools"

  - script: "dotnet cake --Configuration=$(buildConfiguration)"
    displayName: "Run Cake Build Script"

  - task: PublishBuildArtifacts@1
    displayName: "Publish Release Artifact"
    inputs:
      artifactName: Release
      pathToPublish: $(Build.SourcesDirectory)/Artifacts/Build/Release
      publishLocation: Container

  - task: PublishBuildArtifacts@1
    displayName: "Publish Code Coverage Results"
    inputs:
      artifactName: Code Coverage Report
      pathToPublish: $(Build.SourcesDirectory)/Artifacts/Test/CoverageReports/Combined
      publishLocation: Container

  - task: PublishBuildArtifacts@1
    displayName: "Publish Code Coverage Report Artifacts"
    inputs:
      artifactName: CoverageReports
      pathToPublish: $(Build.SourcesDirectory)/Artifacts/Test/CoverageReports
      publishLocation: Container
