trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: Release

steps:
  - displayName: "Restore .NET Tools"
    script: "dotnet tool restore"

  - displayName: "Run Cake Build Script"
    script: "dotnet cake --Configuration=$(buildConfiguration)"

  - displayName: "Publish Code Coverage Results"
    inputs:
      codeCoverageTool: Cobertura
      failIfCoverageEmpty: true
      reportDirectory: $(Build.SourcesDirectory)/Test/CoverageReports/Combined
      summaryFileLocation: $(Build.SourcesDirectory)/Tests/**/coverage.cobertura.xml
    task: PublishCodeCoverageResults@1

  - displayName: "Publish Release Artifact"
    inputs:
      ArtifactName: Release
      PathtoPublish: $(Build.SourcesDirectory)/Artifacts/Build/Release
      publishLocation: Container
    task: PublishBuildArtifacts@1

  - displayName: "Publish Code Coverage Report Artifacts"
    inputs:
      ArtifactName: CoverageReports
      PathtoPublish: $(Build.SourcesDirectory)/Artifacts/Test/CoverageReports
      publishLocation: Container
    task: PublishBuildArtifacts@1
