trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - task: DotNetCoreCLI@2
    displayName: Restore .NET Tools
    inputs:
      command: custom
      custom: tool
      arguments: restore

  - task: DotNetCoreCLI@2
    displayName: Run Cake Build Script
    inputs:
      command: custom
      custom: cake
      arguments: --Target=Publish

  - task: PublishTestResults@2
    displayName: Publish Test Results
    inputs:
      failTaskOnFailedTests: true
      mergeTestResults: true
      testResultsFiles: Tests/**/TestResults/*.trx
      testResultsFormat: VSTest
      testRunTitle: Integration and Unit Tests

  - task: PublishCodeCoverageResults@1
    displayName: Publish Code Coverage Results
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: Artifacts/Test/CoverageReports/Combined/Cobertura.xml
      failIfCoverageEmpty: true

  - task: PublishPipelineArtifact@1
    displayName: Publish Release Artifacts
    inputs:
      artifact: Artifacts
      targetPath: Artifacts
      publishLocation: pipeline

  - task: Docker@2
    displayName: Publish Container Image
    inputs:
      containerRegistry: Docker Hub - Hannah Chan
      repository: hannahchan/scaffold
      command: buildAndPush
      Dockerfile: Artifacts/Build/Scaffold.WebApi/Dockerfile
      buildContext: Artifacts/Build/Scaffold.WebApi/
      tags: |
        latest
        $(Build.BuildId)
        $(Build.SourceVersion)
