trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'tool restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'custom'
    custom: 'cake'
    arguments: '--Configuration=Release'